### ISSUE TITLE
Add support to export to WAV? 

### ISSUE THREAD

**Issue by FlorianEagox** [sayak-brm/espeakng-python#21]
**Is your feature request related to a problem? Please describe.**
I need to be able to export some text made by espeak to a wav file for my repo 

**Describe the solution you'd like**
Add a parameter to the say function which would add a `-w "path"` argument to the command which would tell the binary to save the file.

**Describe alternatives you've considered**
On linux you could just tell it redirect the output with `espeak "hello" > hello.wav"

**Additional context**
I can submit a PR to do this right now if the project is still active, and you'll accept it for a new Pypi release. I'd also like to add a function that just prints all the supported languages from the table linked in your readme.
e.g.
```
def list_voices():
    return ["af","sq","am","ar","an","hy","hyw","as","az","ba","cu","eu","be","bn","bpy","bs","bg","my","ca","chr","yue","hak","haw","cmn","hr","cs","da","nl","en-us","en","en-029","en-gb-x-gbclan","en-gb-x-rp","en-gb-scotland","en-gb-x-gbcwmd","eo","et","fa","fa-latn","fi","fr-be","fr","fr-ch","ga","gd","ka","de","grc","el","kl","gn","gu","ht","he","hi","hu","is","id","ia","io","it","ja","kn","kok","ko","ku","kk","ky","la","lb","ltg","lv","lfn","lt","jbo","mi","mk","ms","ml","mt","mr","nci","ne","nb","nog","or","om","pap","py","pl","pt-br","qdb","qu","quc","qya","pt","pa","piqd","ro","ru","ru-lv","uk","sjn","sr","tn","sd","shn","si","sk","sl","smj","es","es-419","sw","sv","ta","th","tk","tt","te","tr","ug","ur","uz","vi-vn-x-central","vi","vi-vn-x-south","cy"]
```

**Comment by sayak-brm** [comment]
Merged PR #22 and updated the [pypi release](https://pypi.org/project/espeakng/1.0.3/)!
