### ISSUE TITLE
How to Download?

### ISSUE THREAD

**Issue by alislaboratory** [sayak-brm/espeakng-python#7]
Hey, i want to use this library for one of my projects, however ive never used a github library. Could you please let me know how i download this library?

Thanks

**Comment by alislaboratory** [comment]
Its ok! I figured out how to install github libraries.

**Comment by sayak-brm** [comment]
Sorry about the late reply, was busy with college work. I'd like to point
out that this library hasn't been updated in a long time, and is on my
GitHub for archival purposes.

**Comment by sayak-brm** [comment]
However, I may rewrite it soon, considering I have some time on my hands
now. Star this repository to get the notifications for future modifications.

>
