### ISSUE TITLE
OSError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by alislaboratory** [sayak-brm/espeakng-python#8]

**Comment by alislaboratory** [comment]
Trying to `myspeaker.say("Hello world")` however this issue persists. Please let me know if anyone has a fix

**Comment by sayak-brm** [comment]
Can you please tell me which OS are you on?

**Comment by alislaboratory** [comment]
I am on Linux, specifically raspbian.

**Comment by sayak-brm** [comment]
I see. In the directory where you downloaded this repository run the following commands:
```
rm ./espeak
sudo apt-get update
sudo apt-get install espeak
```

As I said, I haven't updated this repo in a long time, and these commands should get you the latest tts engine for your required architecture.

**Comment by sayak-brm** [comment]
Any updates on the issue?

**Comment by alislaboratory** [comment]
I am currently on holidays so I can’t test the fix. I will update you when I get back next week.

**Comment by sayak-brm** [comment]
Okay sure. On a side note, I'm working on updating this library to more recent standards (ESpeak-NG) by the end of this month.

**Comment by sayak-brm** [comment]
Be sure to check out the newer releases for this library. You can install the latest version by using the following commands:

```
sudo apt update
sudo apt install espeak-ng
pip install espeakng
```
Don't forget to remove any older version before doing this.
